default:
  core:
    expriments_root_dir: 'experiments/'
    datastore_name: 'aml_ws_datastore_v2'
    dataset_name: 'diabetes-data'
    ml_cluster_name: 'aml-ws-cluster'
    ml_model_name: 'diabetes-predict-model'
    
  lab_1B: 
    experiment_name: 'azure-ml-sdk-intro'
  
  lab_2B:
    experiment_name: 'datasets-experiment'
    storage_account_name: 'aiclouddata'
    storage_container_name: 'aml-ws-data'
    storage_account_key: '******'
  
  lab_3B:
    experiment_name: 'ml-model-inference-experiment'
    endpoint_uri: ''
    api_key: ''
    
  lab_4A:
    experiment_name: 'my-1st-experiment'
  
  lab_4B:
    experiment_name: 'train-model-experiment'
    working_subdir: 'train-model-experiment-lab'
  
  lab_5A:
    experiment_name: 'environments-experiment'
    working_subdir: 'environments-experiment-lab'
    
  lab_5B:
    experiment_name: 'compute-targets-experiment'
    working_subdir: 'compute-targets-experiment-lab'
    environment_name: 'environments-experiment'
    
  lab_6A:
    experiment_name: 'pipeline-experiment'
    working_subdir: 'pipeline-experiment-lab'
    environment_name: 'environments-experiment'
    
  lab_6B:
    experiment_name: 'pipeline-experiment'
  
  lab_7A:
    experiment_name: 'realtime-service-experiment'
    working_subdir: 'realtime-service-experiment-lab'
    service_name: 'diabetes-predict-service'
    
  lab_7B:
    experiment_name: 'batch-service-experiment'
    working_subdir: 'batch-service-experiment-lab'
    service_name: 'diabetes-predict-service'
    
  lab_8A:
    experiment_name: 'hyperparam-tuning-experiment'
    working_subdir: 'hyperparam-tuning-experiment-lab'
    
  lab_8B:
    experiment_name: 'auto-ml-experiment'
    working_subdir: 'auto-ml-experiment-lab'
