default:
  core:
    expriments_root_dir: 'expriments/'
    datastore_name: 'aml-workshop-data'
    dataset_name: 'diabetes_db'
    ml_cluster_name: 'aml-ws-cluster'
    ml_model_name: 'diabetes-predict-model'
    
  lab_1B: 
    experiment_name: 'azure-ml-sdk-intro'
  
  lab_2B:
    experiment_name: 'dataset-experiment'
    storage_account_name: ''
    storage_container_name: ''
    storage_account_key: ''
  
  lab_3B:
    experiment_name: 'ml-model-inference-experiment'
    endpoint_uri: ''
    api_key: ''
    
  lab_4A:
    experiment_name: 'my-1st-experiment'
  
  lab_4B:
    experiment_name: 'train-model-experiment'
    experiment_tag: ''
  
  lab_5A:
    experiment_name: 'environments-experiment'
    experiment_tag: ''
    
  lab_5B:
    experiment_name: 'compute-targets-experiment'
    experiment_tag: ''
    
  lab_6A:
    experiment_name: 'pipeline-experiment'
    
  lab_6B:
    experiment_name: 'pipeline-experiment'
  
  lab_7A:
    experiment_name: 'realtime-service-experiment'
    experiment_tag: 'RealtimeService'
    
  lab_7B:
    experiment_name: 'batch-service-experiment'
    experiment_tag: 'BatchService'
    
  lab_8A:
    experiment_name: 'hyperparam-tuning-experiment'
    experiment_tag: 'HyperDrive'
    
  lab_8A:
    experiment_name: 'auto-ml-experiment'
    experiment_tag: 'AutoML'
    working_subdir: 'auto-ml-lab'
    
